#!/usr/bin/env bash
# minerva-up — one-command setup + start.
#
# What it does, in order:
#   1. Touches ~/.minerva/cookies.txt so the bind mount always resolves
#      (even on a brand-new machine with no cookies yet).
#   2. Refreshes cookies from your local browser via
#      `python3 minerva-services.py --refresh-cookies <browser>`.
#      Best-effort — if the browser is sandboxed (Snap / Flatpak) or
#      not logged in, it logs and continues.
#   3. Writes docker-compose.override.yml in this directory with the
#      cookies volume mount enabled. Compose auto-loads override files,
#      so subsequent `docker compose up -d` calls keep using it without
#      touching the upstream docker-compose.yml.
#   4. Installs a systemd-user timer that re-runs --refresh-cookies
#      every hour (--install-cookie-timer). One-shot; no-op if already
#      installed.
#   5. `docker compose up -d` and prints the resulting container list.
#
# Usage:
#     ./minerva-up.sh                          # auto-pick browser=firefox
#     MINERVA_BROWSER=chrome ./minerva-up.sh   # use Chrome cookies instead
#     MINERVA_NO_TIMER=1 ./minerva-up.sh       # skip the timer install
#
# Re-run any time you change the docker-compose.yml or want a fresh
# refresh on demand.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
BROWSER="${MINERVA_BROWSER:-firefox}"
COOKIES_DIR="${HOME}/.minerva"
COOKIES_FILE="${COOKIES_DIR}/cookies.txt"
OVERRIDE="${HERE}/docker-compose.override.yml"

mkdir -p "$COOKIES_DIR"

# 1. Stub file so the bind mount has a real target on every host.
if [ ! -e "$COOKIES_FILE" ]; then
  : > "$COOKIES_FILE"
fi

# 2. Best-effort cookie refresh from the user's live browser.
if python3 "$HERE/minerva-services.py" --refresh-cookies "$BROWSER" >/dev/null 2>&1; then
  echo "[minerva-up] cookies refreshed from $BROWSER → $COOKIES_FILE"
elif [ ! -s "$COOKIES_FILE" ]; then
  echo "[minerva-up] no cookies yet — yt-dlp may hit YouTube's bot wall on gated videos."
  echo "             Open $BROWSER, log in to youtube.com, then run this script again."
else
  echo "[minerva-up] keeping the existing cookies.txt (refresh failed for $BROWSER)."
fi

# 3. Drop / refresh the override that mounts cookies.txt into the
#    container. Idempotent.
cat > "$OVERRIDE" <<EOF
# Auto-generated by minerva-up.sh — do not edit by hand.
# Mounts the host's ~/.minerva/cookies.txt into the minerva-services
# container so yt-dlp can authenticate against YouTube.
services:
  minerva-services:
    volumes:
      - ${COOKIES_FILE}:/srv/cookies.txt:ro
EOF
echo "[minerva-up] wrote $OVERRIDE"

# 4. Install the hourly refresh timer (one-shot, idempotent).
if [ "${MINERVA_NO_TIMER:-}" != "1" ] && command -v systemctl >/dev/null 2>&1; then
  if ! systemctl --user is-enabled minerva-cookies.timer >/dev/null 2>&1; then
    if python3 "$HERE/minerva-services.py" --install-cookie-timer "$BROWSER" >/dev/null 2>&1; then
      echo "[minerva-up] hourly refresh timer installed (systemd --user)."
    else
      echo "[minerva-up] could not install timer (systemd --user not available?). Skipping."
    fi
  fi
fi

# 5. Bring the stack up.
cd "$HERE"
docker compose up -d
docker compose ps
